### ISSUE TITLE
Dev mode does not work when installing gem to system

### ISSUE THREAD

**Issue by sloria** [vigosan/big_ml#10]
Need to update the version that is installed using `gem install big_ml` . The newest version includes in client.rb:

```
VALID_OPTIONS_KEYS     = [:username, :api_key, :dev_mode]
```

However, the version from gem install is:

```
VALID_OPTIONS_KEYS     = [:username, :api_key]
```

**Comment by vigosan** [comment]
I have released the 0.1.2 version, please try again and let me know! thanks
