### ISSUE TITLE
Batch prediction

### ISSUE THREAD

**Issue by troelskn** [vigosan/big_ml#11]
Hi,

Documentation is a bit sparse, so I'm having trouble figuring out if I'm taking the right approach here. To predict a single data point, I have the following working:

```
  desc "Predict categories"
  task :predict => :environment do
    model = BigML::Model.find("...")
    product = Product.find(1)
    fields = {
      "000000" => product.name,
      "000001" => product.brand_name,
      "000002" => product.description
    }
    prediction = BigML::Prediction.create(model.resource, :input_data => fields)
    puts "#{prediction.attrs['output']} (#{prediction.attrs['confidence']})"
    prediction.destroy
  end
```

But if I want to predict en masse, this seems rather inefficient. What I'd like to do is to predict a multiple inputs at once. E.g.:

```
  desc "Predict categories"
  task :predict => :environment do
    model = BigML::Model.find("...")
    input_data = []
    Product.each do |product|
      input_data << {
        "000000" => product.name,
        "000001" => product.brand_name,
        "000002" => product.description
      }
    end
    prediction = BigML::Prediction.create(model.resource, :input_data => input_data)
    ...
    prediction.destroy
  end
```

But that doesn't work. Should I create a dataset in this case? And how would the code for that look?

**Comment by troelskn** [comment]
OK, looks like batch predictions are a new addition to bigml's api: https://bigml.com/developers/batch_predictions

That would explain why it isn't supported bi the bindings. Would you like me to contribute an implementation, or are you already working on this?

**Comment by rossmeissl** [comment]
@troelskn can you close this issue now?

**Comment by troelskn** [comment]
Yep
